//! Vhost configuration emitter for projects' Pretty URLs.
//! Uses the same `<<PLACEHOLDER>>` template substitution that Laragon
//! does — files are written under `<scoop_persist>/nginx/conf/stackpilot/`
//! with an `auto.<project>.<host>.conf` filename prefix. Removing the
//! `auto.` prefix from a file freezes it (Stackpilot won't overwrite).
//!
//! v0.3 ships nginx HTTP-only. SSL + Apache + Caddy are v0.4.

use std::fs;
use std::path::{Path, PathBuf};

use crate::projects::{Project, VHost};
use crate::ssl;

/// Subdirectory inside `<scoop_persist>/nginx/conf/` that Stackpilot owns.
pub const NGINX_VHOSTS_SUBDIR: &str = "stackpilot";

/// Marker comment inside nginx.conf for the include directive Stackpilot
/// adds the first time a vhost is created.
pub const INCLUDE_MARKER: &str = "# stackpilot-vhosts: managed include";

const NGINX_HTTP_TEMPLATE: &str = r#"# Auto-generated by Stackpilot. Remove the `auto.` prefix to freeze this file.
# Project: <<PROJECT>>
server {
    listen <<PORT>>;
    server_name <<HOST>> *.<<HOST>>;
    root "<<DOCUMENT_ROOT>>";

    index index.html index.htm index.php;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
        autoindex on;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass 127.0.0.1:9000;
    }

    charset utf-8;
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
    location ~ /\.ht { deny all; }
}
"#;

const NGINX_HTTPS_TEMPLATE: &str = r#"# Auto-generated by Stackpilot. Remove the `auto.` prefix to freeze this file.
# Project: <<PROJECT>>
server {
    listen <<PORT>>;
    listen <<SSL_PORT>> ssl;
    server_name <<HOST>> *.<<HOST>>;
    root "<<DOCUMENT_ROOT>>";

    ssl_certificate     "<<SSL_CRT>>";
    ssl_certificate_key "<<SSL_KEY>>";
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    index index.html index.htm index.php;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
        autoindex on;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass 127.0.0.1:9000;
    }

    charset utf-8;
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
    location ~ /\.ht { deny all; }
}
"#;

/// Path of the nginx-managed vhosts dir under the active Scoop install.
pub fn nginx_vhosts_dir(scoop_root: &Path) -> PathBuf {
    scoop_root
        .join("persist")
        .join("nginx")
        .join("conf")
        .join(NGINX_VHOSTS_SUBDIR)
}

pub struct EmitOutcome {
    pub written: Vec<PathBuf>,
    pub warnings: Vec<String>,
}

/// Emit per-vhost config files for a project. Files we wrote on a previous
/// activate are pruned first so the generated set always reflects the
/// current project state. SSL vhosts also get a cert + key minted via
/// OpenSSL; failures here become warnings (we still emit an HTTP-only
/// vhost as a fallback).
pub fn emit(project: &Project, scoop_root: &Path) -> Result<EmitOutcome, String> {
    let dir = nginx_vhosts_dir(scoop_root);
    fs::create_dir_all(&dir).map_err(|e| format!("create vhosts dir: {e}"))?;

    cleanup(project, scoop_root)?;

    let mut written = Vec::new();
    let mut warnings = Vec::new();
    for vh in &project.vhosts {
        if vh.host.trim().is_empty() {
            continue;
        }
        if vh.server.as_str() != "nginx" {
            continue;
        }
        let path = dir.join(filename_for(project, vh));
        let body = if vh.ssl {
            match ssl::mint(&vh.host) {
                Ok(certs) => render_nginx_https(project, vh, &certs),
                Err(e) => {
                    warnings
                        .push(format!("SSL for {} disabled: {}", vh.host, e));
                    render_nginx_http(project, vh)
                }
            }
        } else {
            render_nginx_http(project, vh)
        };
        fs::write(&path, body).map_err(|e| format!("write {}: {e}", path.display()))?;
        written.push(path);
    }
    Ok(EmitOutcome { written, warnings })
}

/// Delete all auto.<project-key>.*.conf files we may have left behind.
pub fn cleanup(project: &Project, scoop_root: &Path) -> Result<(), String> {
    let dir = nginx_vhosts_dir(scoop_root);
    if !dir.exists() {
        return Ok(());
    }
    let prefix = format!("auto.{}.", project.key);
    let rd = fs::read_dir(&dir).map_err(|e| format!("read vhosts dir: {e}"))?;
    for entry in rd.flatten() {
        let name = entry.file_name();
        let Some(s) = name.to_str() else { continue };
        if s.starts_with(&prefix) && s.ends_with(".conf") {
            let _ = fs::remove_file(entry.path());
        }
    }
    Ok(())
}

/// Sanitize host into a filename-safe stub.
fn filename_for(project: &Project, vh: &VHost) -> String {
    let safe_host: String = vh
        .host
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '.' { c } else { '_' })
        .collect();
    format!("auto.{}.{}.conf", project.key, safe_host)
}

fn render_nginx_http(project: &Project, vh: &VHost) -> String {
    let document_root = if vh.document_root.trim().is_empty() {
        project.root_dir.clone()
    } else {
        vh.document_root.clone()
    };
    NGINX_HTTP_TEMPLATE
        .replace("<<PROJECT>>", &project.name)
        .replace("<<PORT>>", &vh.port.to_string())
        .replace("<<HOST>>", &vh.host)
        .replace("<<DOCUMENT_ROOT>>", &document_root.replace('\\', "/"))
}

fn render_nginx_https(project: &Project, vh: &VHost, certs: &ssl::CertPaths) -> String {
    let document_root = if vh.document_root.trim().is_empty() {
        project.root_dir.clone()
    } else {
        vh.document_root.clone()
    };
    let ssl_port = if vh.port == 80 { 443 } else { vh.port + 363 };
    NGINX_HTTPS_TEMPLATE
        .replace("<<PROJECT>>", &project.name)
        .replace("<<PORT>>", &vh.port.to_string())
        .replace("<<SSL_PORT>>", &ssl_port.to_string())
        .replace("<<HOST>>", &vh.host)
        .replace("<<DOCUMENT_ROOT>>", &document_root.replace('\\', "/"))
        .replace("<<SSL_CRT>>", &certs.crt.display().to_string().replace('\\', "/"))
        .replace("<<SSL_KEY>>", &certs.key.display().to_string().replace('\\', "/"))
}

/// Make sure nginx.conf includes the stackpilot directory. Returns true if
/// the file was modified (caller may want to log / surface). The added
/// snippet is fenced with `INCLUDE_MARKER` so subsequent invocations are
/// idempotent.
pub fn ensure_nginx_include(scoop_root: &Path) -> Result<bool, String> {
    let conf = scoop_root
        .join("persist")
        .join("nginx")
        .join("conf")
        .join("nginx.conf");
    if !conf.exists() {
        return Ok(false); // nginx not initialized yet — caller will surface.
    }
    let body = fs::read_to_string(&conf).map_err(|e| format!("read nginx.conf: {e}"))?;
    if body.contains(INCLUDE_MARKER) {
        return Ok(false);
    }

    // Find `http {` block and insert just after the opening brace.
    let Some(http_idx) = body.find("http {") else {
        return Err("nginx.conf has no `http {` block to inject into".into());
    };
    let insertion_point = http_idx
        + body[http_idx..]
            .find('{')
            .ok_or_else(|| "couldn't locate http block opening brace".to_string())?
        + 1;

    let snippet = format!(
        "\n    {}\n    include  {}/*.conf;\n",
        INCLUDE_MARKER, NGINX_VHOSTS_SUBDIR
    );

    let mut updated = String::with_capacity(body.len() + snippet.len());
    updated.push_str(&body[..insertion_point]);
    updated.push_str(&snippet);
    updated.push_str(&body[insertion_point..]);

    let bak = conf.with_extension("conf.bak");
    let _ = fs::write(&bak, &body);
    fs::write(&conf, updated).map_err(|e| format!("write nginx.conf: {e}"))?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(host: &str, port: u16) -> (Project, VHost) {
        let project = Project {
            key: "myapp".into(),
            name: "MyApp".into(),
            root_dir: "C:\\code\\myapp".into(),
            services: vec![],
            env_vars: std::collections::BTreeMap::new(),
            notes: String::new(),
            vhosts: vec![],
            created_at: 0,
            last_active_at: None,
        };
        let vh = VHost {
            host: host.into(),
            port,
            document_root: String::new(),
            server: "nginx".into(),
            ssl: false,
        };
        (project, vh)
    }

    #[test]
    fn render_substitutes_placeholders() {
        let (p, vh) = fixture("myapp.test", 80);
        let out = render_nginx_http(&p, &vh);
        assert!(out.contains("server_name myapp.test *.myapp.test"));
        assert!(out.contains("listen 80;"));
        assert!(out.contains("root \"C:/code/myapp\";"));
        assert!(out.contains("# Project: MyApp"));
    }

    #[test]
    fn render_uses_doc_root_override() {
        let (p, mut vh) = fixture("myapp.test", 80);
        vh.document_root = "D:\\sites\\myapp\\public".into();
        let out = render_nginx_http(&p, &vh);
        assert!(out.contains("root \"D:/sites/myapp/public\";"));
    }

    #[test]
    fn filename_is_safe() {
        let (p, vh) = fixture("my app/test", 80);
        let f = filename_for(&p, &vh);
        assert_eq!(f, "auto.myapp.my_app_test.conf");
    }

    #[test]
    fn ensure_include_inserts_then_idempotent() {
        let tmp = std::env::temp_dir().join(format!(
            "stackpilot-vhost-test-{}",
            std::process::id()
        ));
        let conf_dir = tmp.join("persist").join("nginx").join("conf");
        std::fs::create_dir_all(&conf_dir).unwrap();
        let conf = conf_dir.join("nginx.conf");
        std::fs::write(
            &conf,
            "events {}\nhttp {\n    include       mime.types;\n}\n",
        )
        .unwrap();

        let changed = ensure_nginx_include(&tmp).unwrap();
        assert!(changed, "first call should insert include");
        let body = std::fs::read_to_string(&conf).unwrap();
        assert!(body.contains(INCLUDE_MARKER));
        assert!(body.contains(&format!("include  {NGINX_VHOSTS_SUBDIR}/*.conf;")));

        let changed2 = ensure_nginx_include(&tmp).unwrap();
        assert!(!changed2, "second call should be a no-op");

        std::fs::remove_dir_all(&tmp).ok();
    }
}
